---
apiVersion: v1
kind: ConfigMap
metadata:
  name: packagemanage-config
data:
  conf.yaml: |
    - dbname: openEuer_20.03_LTS_x86
      src_db_file:
      - /etc/database/source_repodata.sqlite
      bin_db_file:
      - /etc/database/everything_x86_64.sqlite
      status: enable
      priority: 1
    - dbname: openEuer_20.03_LTS_aarch64
      src_db_file:
      - /etc/database/source_repodata.sqlite
      bin_db_file:
      - /etc/database/everything_aarch64.sqlite
      status: enable
      priority: 1
  package.ini: |
    [SYSTEM]

    ; Configuration file path for data initialization
    init_conf_path=/etc/pkgship/conf.yaml

    ; Whether the system is in debug mode
    debug=false

    ; Where to store data files when using sqlite database
    ; data_base_path=/var/run/pkgship_dbs

    ; Port managed by the administrator, with write permission

    write_port=8080

    ; Ordinary user query port, only the right to query data, no permission to write data

    query_port=8090

    ; IP address path with write permission

    write_ip_addr=0.0.0.0

    ; IP address path with permission to query data

    query_ip_addr=0.0.0.0


    [DATABASE]

    ; Basic configuration of sqlalchemy to connect to the database

    ;Username of the database
    user_name=

    ;connection password
    password=

    ;host address
    host=

    ; number for database connection
    port=

    ;Connected data name
    database=

    ; dbtype:The type of database is mainly divided into mysql and sqlite
    dbtype=sqlite

    [LOG]

    ; Custom log storage path
    ; log_path=/var/run/pkgship

    ; Logging level
    ; The log level option value can only be as follows
    ; INFO DEBUG WARNING ERROR CRITICAL
    log_level=INFO

    ; logging name
    log_name=log_info.log

    [UWSGI]

    daemonize=/var/log/uwsgi.log

    buffer-size=65536



