---
apiVersion: v1
kind: ConfigMap
metadata:
  name: packagemanage-config
data:
  conf.yaml: |
    - dbname: bringInRely
      src_db_file: /etc/database/bringInRely_src.sqlite
      bin_db_file: /etc/database/bringInRely_bin.sqlite
      lifecycle: enable
      priority: 1
    - dbname: fedora30
      src_db_file: /etc/database/fedora30_src.sqlite
      bin_db_file: /etc/database/fedora30_bin.sqlite
      lifecycle: enable
      priority: 1
    - dbname: mainline
      src_db_file: /etc/database/mainline_src.sqlite
      bin_db_file: /etc/database/mainline_bin.sqlite
      lifecycle: enable
      priority: 1
    - dbname: openEuer
      src_db_file: /etc/database/openEuler-src.sqlite
      bin_db_file: /etc/database/openEuler-bin.sqlite
      lifecycle: enable
      priority: 1
  package.ini: |
    [SYSTEM]

    ; Configuration file path for data initialization
    init_conf_path=/etc/pkgship/conf.yaml

    ; Whether the system is in debug mode
    debug=false

    ; Where to store data files when using sqlite database
    ; data_base_path=/var/run/pkgship_dbs

    ; Port managed by the administrator, with write permission

    write_port=8080

    ; Ordinary user query port, only the right to query data, no permission to write data

    query_port=8090

    ; IP address path with write permission

    write_ip_addr=0.0.0.0

    ; IP address path with permission to query data

    query_ip_addr=0.0.0.0

    ; The address of the remote service, the command line can directly 
    ; call the remote service to complete the data request
    remote_host=https://api.openeuler.org/pkgmanage

    [DATABASE]

    ; Basic configuration of sqlalchemy to connect to the database

    ;Username of the database
    user_name=

    ;connection password
    password=

    ;host address
    host=

    ; number for database connection
    port=

    ;Connected data name
    database=

    ; dbtype:The type of database is mainly divided into mysql and sqlite
    dbtype=sqlite

    [LOG]

    ; Custom log storage path
    ; log_path=/var/run/pkgship

    ; Logging level
    ; The log level option value can only be as follows
    ; INFO DEBUG WARNING ERROR CRITICAL
    log_level=INFO

    ; logging name
    log_name=log_info.log

    [UWSGI]

    ; uwsgi log file path
    daemonize=/var/log/uwsgi.log
    
    ; The data size transferred from back to forth
    buffer-size=65536

    ; HTTP Connection time
    http-timeout=600

    ; Server response time
    harakiri=600

