---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-pkgship-db-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ssd
